steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'Dockerfile.prod'
      - '--build-arg'
      - 'VITE_API_BASE_URL=https://instaviz-backend-394992534886.asia-northeast1.run.app'
      - '-t'
      - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/instaviz/frontend:latest'
      - '.'

images:
  - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/instaviz/frontend:latest'
