steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'Dockerfile.prod'
      - '--build-arg'
      - 'VITE_API_BASE_URL=https://instaviz-backend-v2kw6uhafa-an.a.run.app'
      - '--build-arg'
      - 'VITE_FIREBASE_API_KEY=AIzaSyBYRZGFb2Sa5Oa3yvx1EEUIjI4InthEA_c'
      - '--build-arg'
      - 'VITE_FIREBASE_AUTH_DOMAIN=instaviz-f9110.firebaseapp.com'
      - '--build-arg'
      - 'VITE_FIREBASE_PROJECT_ID=instaviz-f9110'
      - '-t'
      - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/instaviz/frontend:latest'
      - '.'

images:
  - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/instaviz/frontend:latest'
